language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y libudev-dev
  - ls -la
  - grep secret *.yaml`
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
