homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  customize: !include customizations.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password

group: !include_dir_merge_named groups

device_tracker: !include device_tracker.yaml

zone: !include_dir_list zones

script: !include_dir_merge_named scripts

sensor: !include_dir_merge_list sensors

logger:
  default: warning
  logs:
#    homeassistant.components.sensor.google_travel_time: debug
    homeassistant.components.recorder: debug
#    homeassistant.components.sensor.fritz: debug
#    homeassistant.components.sensor.nmap: debug
