- platform: google_travel_time
  name: To home (car)
  api_key: !secret GOOGLE_API
  origin: device_tracker.homeassistant_jonathan
  destination: zone.home

- platform: google_travel_time
  name: To home (bike)
  api_key: !secret GOOGLE_API
  origin: device_tracker.homeassistant_jonathan
  destination: zone.home
  mode: bicycling
  icon: mdi:bike

- platform: google_travel_time
  name: To work (car)
  api_key: !secret GOOGLE_API
  origin: device_tracker.homeassistant_jonathan
  destination: zone.werk_maastricht

- platform: google_travel_time
  name: To work (bike)
  api_key: !secret GOOGLE_API
  origin: device_tracker.homeassistant_jonathan
  destination: zone.werk_maastricht
  mode: bicycling
  icon: mdi:bike

- platform: google_travel_time
  name: To Venlo (car)
  api_key: !secret GOOGLE_API
  origin: device_tracker.homeassistant_jonathan
  destination: zone.work_v